apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/created-by: modeldynamics-helix
    app.kubernetes.io/managed-by: modeldynamics
    app.kubernetes.io/name: test99
    app.kubernetes.io/part-of: helix-project
  name: test99
  namespace: argocd
spec:
  destination:
    namespace: helix-test99
    server: https://kubernetes.default.svc
  project: test99
  source:
    helm:
      valueFiles:
      - values.yaml
    path: .
    repoURL: git@github.com:lukemarsden/helix-test
    targetRevision: HEAD
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 30s
      limit: -1
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=background
    - PruneLast=true
