apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sk-learn-random-forest-reg
  namespace: helix-project-0
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://helix-test/0/afcc985b8df2463bafc3d1e81db5fdf7/artifacts/model
    serviceAccountName: sk-learn-random-forest-reg
