apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sk-learn-random-forest-reg3
  namespace: helix-project-0
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://helix-test/0/a402826027b34fd98647d6fa0d76a005/artifacts/model
    serviceAccountName: sk-learn-random-forest-reg3
