apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sk-learn-random-forest-reg-test1
  namespace: helix-project-0
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://helix-test/0/11b97c39a86545bf95fbd34c69ac2d16/artifacts/model
    serviceAccountName: sk-learn-random-forest-reg-test1
