apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sk-learn-random-forest-reg-demo
  namespace: helix-project-0
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://helix-test/0/2ca6a2a29960441f9b87b049f7b3682b/artifacts/model
    serviceAccountName: sk-learn-random-forest-reg-demo
