apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sk-learn-random-forest-reg-3
  namespace: helix-project-0
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://helix-test/0/f8da161145f94f84ab8c27680daa3b07/artifacts/model
    serviceAccountName: sk-learn-random-forest-reg-3
