apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: sk-learn-random-forest-reg-1
  namespace: helix-project-0
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://helix-test/0/b7fe17427c9940779317214f50f4ef40/artifacts/model
    serviceAccountName: sk-learn-random-forest-reg-1
